# Generated by Django 4.2.4 on 2024-02-21 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myport', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='joshuamail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
            ],
            options={
                'db_table': 'joshuamail',
            },
        ),
        migrations.AlterModelTable(
            name='mail',
            table='mail',
        ),
    ]
